name: Starter Workflow
on: [workflow_dispatch, push, pull_request]

jobs:
  call-generate-readme-workflow:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: Keyfactor/actions/.github/workflows/generate-readme.yml@main

  call-update-catalog-workflow:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: Keyfactor/actions/.github/workflows/update-catalog.yml@main
    secrets: 
      token: ${{ secrets.SDK_SYNC_PAT }}